-- MySQL Script generated by MySQL Workbench
-- Thu Aug 17 12:07:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`emprendimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprendimientos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `foto_card` VARCHAR(45) NOT NULL,
  `foto_emprendimiento` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `descuento` INT NOT NULL,
  `stock` INT NOT NULL,
  `emprendimientos_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`, `categoria_id`),
  CONSTRAINT `fk_productos_emprendimientos1`
    FOREIGN KEY (`emprendimientos_id`)
    REFERENCES `mydb`.`emprendimientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_productos_emprendimientos1_idx` ON `mydb`.`productos` (`emprendimientos_id` ASC) VISIBLE;

CREATE INDEX `fk_productos_categoria1_idx` ON `mydb`.`productos` (`categoria_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`imagenes_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`imagenes_productos` (
  `id` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `productos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_imagenes_productos_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `mydb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_imagenes_productos_productos1_idx` ON `mydb`.`imagenes_productos` (`productos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`punto_de_retiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`punto_de_retiro` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `id` INT NOT NULL,
  `forma_retiro` VARCHAR(45) NOT NULL,
  `estado_del_pedido` VARCHAR(45) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `clientData` TEXT NOT NULL,
  `punto_retiro_id` INT NOT NULL,
  `numero_orden` VARCHAR(45) NOT NULL,
  `tipo_de_entrega` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `punto_retiro_id`),
  CONSTRAINT `fk_pedidos_punto_retiro1`
    FOREIGN KEY (`punto_retiro_id`)
    REFERENCES `mydb`.`punto_de_retiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedidos_punto_retiro1_idx` ON `mydb`.`pedidos` (`punto_retiro_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`notificaciones_mp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notificaciones_mp` (
  `id` INT NOT NULL,
  `idPedido` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
